### ISSUE TITLE
Sproglag på mulige markedsroller i Datahub (dansk/engelsk)

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#1006]
Baggrund:
Listen over mulige markedsroller i DH3 skal tilpasses det valgte sproglag

Som DH3 medarbejder
Vil jeg - når jeg opretter en aktør i DataHub 3 kunne vælge mellem markedsroller på dansk eller engelsk  
For at gøre det lettere at finde den rigtige markedsrolle

Mulige roller er i det vedhæftede regneark. 
Rollerne med mørk skrift skal være på listen i DataHub 3
Det er kolonnen 'Rollenavn' der er relevant

- [ ] De eksisterende markedsrollenavne i DataHub er på engelsk (kolonne A)
- [ ] De eksisterende markedsrollenavne i DataHub er på dansk (kolonne B)
- [ ] Eksport af brugerroller er ligeledes oversat og matcher sortering i tabellen

Note: Der findes markedsroller, der ikke er oversat til engelsk. Brug her de danske titler

[https://app.zenhub.com/files/337536836/0445522c-6d44-4368-8319-fed0a6bcf6dd/download](https://app.zenhub.com/files/337536836/0445522c-6d44-4368-8319-fed0a6bcf6dd/download)

**Comment by ENDK-RHC** [comment]
RHC - Testet OK i forhold til at GUI skal omskrives på et senere tidspunkt.
