### ISSUE TITLE
1.4 Fills invite user form, send invite link - logning

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#1011]
Som DH support
Vil jeg gerne kunne bevise overfor aktører at deres mailinvitation reelt er sendt ud af Energinet
For at kunne lette supportarbejdet

Den mail der afsendes fra #1009 (invitationsmailen til DataHub) skal 'logges'

AC
- [x] Mailen skal sendes BCC til en supportpostkasse - vi bruger datahub@energinet.dk

Denne er angivet som ønsket BCC: webformlog@energinet.dk  @ENDK-RHC

**Comment by xnetsrak** [comment]
Hvad med test mails i de forskellige miljøer, hvor skal de ramme ? Går ikke ud fra alle skal ramme samme postkasse ?

**Comment by xnetsrak** [comment]
Der er noget usikkerhed omkring hvilken mail der sendes fra, og med bcc .
Vend gerne dette internt igen i forretningen og sammen med MD/Outlaws som har styr på indstillingerne i SendGrid.

**Comment by Tm1807** [comment]
@xnetsrak: Det er den samme postkasse, der skal rammes fra alle miljøer
Den tidligere angivne postkasse kan vel bruges som afsenderadresse?
Det er i hvert tilfælde det vi går med fra starten af!
