### ISSUE TITLE
1.1 Oprettelse af bruger

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#1027]
Som aktør-brugeradmin vil jeg:
Kunne invitere en bruger til DataHub og angive foruddefinerede brugerroller
Så brugeren kan få adgang til aktørens data.

Forudsætning:
Der er anmodet om brugeroprettelse til brugeradmin (mundtligt/skriftligt). Ønsker om rettigheder er kendt.
Navn, emailadresse + telefonnummer samt rettigheder og aktør/markedsrolle.
Bruger er ikke oprettet i forvejen. Note: Hvis brugeren er oprettet i forvejen, så skal der dirigeres til 'rediger bruger'-siden (siden er ikke i denne feature)

- [x] Brugerens rigtige navn skal angives
- [x] Brugeradmin skal angive mailadresse (validering: indenfor eget domæne løses med #1012)
- [x] Brugeradmin skal angive brugerroller
- [x] Brugeradmin skal angive telefonnummer til brugeren (til 2FA)
- [x] Aktørangivelse
- [x] Brugeren fremgår på listen over brugere

#### Backend
- [x] Create endpoint for inviting a user in AD and dbo.User. (aiu)
- [x] Oprydning af Email væk fra User (aiu)
- [x] Manglende fejlbesked i GetGridAreaAuditLogEntriesHandler
- [x] Tilfældig adgangskode, som lever op til password-krav (mjm)
- [x] Opdater pakke mod BFF
- [x] Indsæt devDataHubB2C.onmicrosoft.com korrekt fra client/config/somewhere
- [x] Kontroller at alle TODOs er fjernet fra koden, så ikke noget er glemt
- [x] UTs af:
   - [x] UserInvitation
   - [x] UserInvitationService
   - [x] GetUserPermissionsHandler
   - [x] InviteUserHandler
   - [x] InviteUserCommandRuleSet
   - [x] UserIdentityAuthenticationService
   - [x] UserIdentityRepository

#### Frontend 
- [x] Add invite user button (mvt)
- [x] Add invite user modal
- [x] Add step component
- [x] Add user form fields with validation
- [x] Add user role selector
- [x] Create user on save

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Organisationer-og-akt%C3%B8rer---Brugere%2C-roller-og-rettigheder?node-id=12%3A4240&t=ISgDwJc0DH0HSkid-1

**Comment by defectiveAi** [comment]
Kan man invitere en bruger i en aktør med status: Aktiv, Inaktiv, Passiv eller Ny?
Kan man invitere en bruger i en organisation med status: Aktiv, Blokeret, Slettet eller Ny?

**Comment by ENDK-RHC** [comment]
Man man inviter efter følgende regler.

Aktør.
Kan Inviter :Aktiv, Passiv og NY
Kan ikke inviter: Inaktiv

Organisation:
Kan inviter: Aktiv, Blokeret og Ny
Kan ikke inviter: Slettet
