### ISSUE TITLE
Historik

### ISSUE THREAD

**Issue by FirestarJes** [Energinet-DataHub/ARCHIVED-geh-post-office#636]
Som bruger har jeg behov for at kunne se, hvem der har oprettet/redigeret en rettighed, samt hvornår det er sket. Der er ikke behov for GUI, men det skal være muligt at lave et udtræk.

#### Accept criteria
- [ ] Det er muligt at trække en rapport over handlinger foretaget på en specifik rettighed, indeholdende bruger og tidspunkt for hver handling.

#### Technical tasks
- [ ] Bruger context i markpart
- [ ] Generisk AuditLogRepository/Service
- [ ] AuditLog-tabel (context, message, user, timestamp)

#### Notes fra PI
- API til udtræk af data
- Bruger context
- Database
  - Bruger
  - Tidspunkt
  - Handling

**Comment by Tm1807** [comment]
@michaelmajgaard: Denne kan lukkes (indholdet er overført til #909)

**Comment by Tm1807** [comment]
Løst i andre opgaver
