### ISSUE TITLE
Opret Brugerrolle

### ISSUE THREAD

**Issue by FirestarJes** [Energinet-DataHub/ARCHIVED-geh-post-office#638]
Som DataHub ønskes det at BrugerRoller kan oprettes og gøres det muligt at lave en samling af rettigheder. 
Dette vil gøre det muligt at afgrænse dele af systemet, så kun brugere med den enkelte rettighed har adgang til bestemte ressourcer. 

- Vi får brug for
  - [ ] SQL
  - [ ] UI
  - [ ] API

---

For at gøre dette har vi brug for at beskrive en brugerrolle i en datamodel:
 
UserRoles Tabel:
UserRoles
Id, primær
Navn
Beskrivelse
(OrgansationsId) ?

Der er behov for en relations tabel mellem rettigheder og en Bruger rolle.

UserRoles->Rettigheder Tabel:
UserRoleRights:
Id
RightId
UserRoleId

---

Oprettelse af API til at kunne opsætte brugerroller. 
Brug for at kunne.
- Oprette Brugerrolle.
- Slette/Rediger brugerrolle (beskrivelse)
- Tilknytte of fjerne rettigheder.
- Validering ? 

--

Der skal laves brugergrænseflade for at kunne:
- Oprette brugerrolle, (id, orgId, beskrivelse. )
- Tilføje fjerne rettigheder fra brugerrolle

**Comment by Tm1807** [comment]
Løst i andre opgaver
