### ISSUE TITLE
Opret Rettighed

### ISSUE THREAD

**Issue by FirestarJes** [Energinet-DataHub/ARCHIVED-geh-post-office#640]
Som bruger med rettighed til at "oprette rettigheder" har jeg behov for at kunne oprette en rettighed med følgende data:
    - Navn (Påkrævet)
    - Gruppe (Påkrævet)
Hvis jeg ikke indtaster korrekte eller påkrævede felter, skal jeg præsenteres for en fejlbesked således at jeg bliver informeret korrekt om hvad jeg mangler at udfylde.

Det skal være muligt at oprette disse rettigheder via GUI, det er dog ikke påkrævet at kunne se dem i GUI endnu.

For at understøtte dette er der behov for (Accept Criteria):
  - [ ] API
    - [ ] Create
      - [ ] Validering
        - [ ] Unikt navn
        - [ ] Navn påkrævet
        - [ ] Gruppe påkrævet
        - [ ] Visning af resultat i GUI
    - [ ] List permission groups
  - [ ] Database
    - [ ] Permission Table
      - [ ] Id, primær
      - [ ] Name, Unique
      - [ ] PermissionGroupId, Foreignkey til PermissionGroupTable
    - [ ] PermissionGroup Table
      - [ ] Id, Primær
      - [ ] Name

Det er antaget at der findes værdier i Permissiongroup tabellen. For denne opgave skal de manuelt oprettes, da de skal bruges for at kunne levere ovenstående funktionalitet. Den korrekte oprettelse osv. af disse håndteres i en anden opgave.

**Comment by Tm1807** [comment]
Løst i andre opgaver
