### ISSUE TITLE
[Titans] Roller/rettigheder: 3 Som en bruger logget ind i DH skal jeg kunne skifte mellem aktører/markedsroller

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#838]
Dette ændrer adgangsrettigheder!

Som en bruger der er tilknyttet flere forskellige aktører/markedsroller
Skal jeg kunne skifte mellem disse aktører/markedsroller
For nemt (som bruger) at kunne håndtere flere forskellige aktører

Obs: Ingen bevidst log-ud/log-ind for at skifte mellem aktørerne. Der tænkes et klik i øverste højre hjørne for at vælge mellem forskellige aktører/markedsroller

Behov: På hvilket niveau skal rettighederne kobles?
Organisation - Aktør - Markedsrolle - Netområde

AC
- [x] For en bruger med tilknytning til flere forskellige aktører/markedsroller kan der nem skiftes mellem aktørerne/markedsrollerne
- [x] En bruger, der skifter aktør skal rolle/rettighedsopdateres uden 'front'-logout/login
- [x] UI

https://www.figma.com/file/fwEDQkgEcpwfUojXl0EIC5/Watt-Design-System?node-id=4779%3A12038&t=Pzclaz26h13fMTsC-1

[Roller og rettigheder a.jpg](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/69d293a4-9d34-48e1-a332-d34bfeb9fae0)

**Comment by defectiveAi** [comment]
Fra Feature 2:
- Der er indtil videre kun FAS brugere, som alle tilhører den samme Energinet-aktør.
- Skifte mellem aktører er først lavet i Feature 3.
- Derfor holder vi Energinet-aktør på 'frontend'-app registration.
- Effekten af det er, at man kan rettighedsstyre DataHub globalt, og ikke per aktør (endnu).

**Comment by Tm1807** [comment]
Som en bruger der er tilknyttet flere forskellige aktører
Skal jeg kunne skifte mellem disse aktører (og brugerroller)
For nemt at kunne håndtere flere forskellige aktører

Obs: Ingen bevidst log-ud/log-ind for at skifte mellem aktørerne. Der tænkes et klik i øverste højre hjørne for at vælge mellem forskellige aktører
