### ISSUE TITLE
Oversigt over eksisterende rettigheder i DH GUI

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#894]
### Synopsis
Som en DataHub-bruger skal jeg kunne se en oversigt over alle rettigheder i DataHub UI
for at kunne danne mig et overblik.
_____________
### Acceptance Criteria
- [x] En DataHub bruger skal kunne se en oversigt over rettigheder i DataHub i UI.
Felter:
- [x] Rettighedsnavn
- [x] Beskrivelse af rettighed
- [x] Listen sorteres indledningsvis efter rettighedsnavn

Note: 'Status' er fjernet fuldstændigt
________________
### Tech. Notes

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Brugeradministration?node-id=29%3A4902&t=XXyhLop8uyj7WVek-1
________________

#### Backend
- [x] Get all permissions
#### Frontend
- [x] Add table with permissions
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
- [ ] Verified by UX

_________________
#### How to test
Enviroment:
User:
Senario:

**Comment by defectiveAi** [comment]
@Tm1807 Vi har spillet om denne opgave, men foreslår at splitte den i to. Den anden opgave vil så indeholde "Ved klik på rettigheden skal der kunne ses yderligere oplysninger på rettigheden (hvilke markedsroller og brugerroller indgår rettigheden i)"

**Comment by Tm1807** [comment]
@defectiveAi 'Fly-in' ("Ved klik på rettigheden skal der kunne ses yderligere oplysninger på rettigheden (hvilke markedsroller og brugerroller indgår rettigheden i)") er nu udtaget og lagt i #1058. 
Note: 'Status' er fjernet fuldstændigt fra 'Rettigheder' (også fra denne opgave)

**Comment by mimse** [comment]
@Tm1807 

Skal det være muligt at søg og download rettighederne som vist her

![image.png](https://images.zenhubusercontent.com/633fbb34b49ff882a80234ab/642ca1ab-37ee-4212-8db7-8f7783b31c78)

**Comment by Tm1807** [comment]
@mimse 
'Skal det være muligt at søg og download rettighederne som vist her'
Ja tak
