### ISSUE TITLE
[Titans] Liste med markedsroller

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#964]
Der skal vises en liste over eksisterende markedsroller

Som en DataHub bruger 
Vil jeg gerne kunne se en oversigt over eksisterende markedsroller i DataHub

Note: Oprettelse og beskrivelse af markedsroller sker backend. Dette er kun visning i GUI

AC
- [x] En oversigt over eksisterende markedsroller i DataHub
- [x] Beskrivelse af markedsrollen
- [x] UI

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Organisationer-og-akt%C3%B8rer---Brugere%2C-roller-og-rettigheder?node-id=32%3A5537&t=QFya6aPqqbWRvUDh-1

Liste med aktørroller er vedhæftet. Bemærk: der er mange roller, der ikke skal bruges. Det er som udgangspunkt kun de sorte roller, der skal bruges.
[https://app.zenhub.com/files/337536836/ab0dcd60-bccf-465e-8fe1-b31bbe746ff3/download](https://app.zenhub.com/files/337536836/ab0dcd60-bccf-465e-8fe1-b31bbe746ff3/download)!

**Comment by michaelmajgaard** [comment]
@Tm1807 Følgende mangler danske og engelske beskrivelser:

System Operator (DK rolle)
Energistyrelsen (DK rolle)
ElOverblik (DK rolle)
DataHub Administrator (DK rolle)
Uafhængig aggregator (DK rolle)
Seriel elhandler (DK rolle)

**Comment by Tm1807** [comment]
@michaelmajgaard Det er modtaget - jeg får (sammen med 1. line) udfyldt de manglende ting. Du hører nærmere.

**Comment by michaelmajgaard** [comment]
Ift. test, så ligger det ny skærmbillede under Organisation i en ny tab 'Markedsroller'. Test gerne sortering i listen samt at den dowloadede CSV matcher sorteringen i skærmbilledet. Test også gerne oversættelse virker for navn og beskrivelse af markedsrollerne i tabellen (skal ligeledes være oversat i CSV'en). Kolonneoverskrifter oversættes ikke når man skifter sprog. Dette er en bug i tabel-komponenten, og UI/UX er bevidst om denne.
@ENDK-RHC @Tm1807
