### ISSUE TITLE
Listen over brugere skal indeholde aktørnavn og GLN

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#993]
Listen over brugere skal også indeholde aktørnavn og GLN

AC:
- [x] Listen over brugere skal også indeholde aktørnavn 
> Anden opgave (882)
- [x] > Listen over brugere skal også indeholder GLN (882)
> Anden opgave (882)
- [x] Listen kan filtreres på GLN/aktørnavn
- [x] Listen kan filtreres på brugerrolle

![2023-01-19_13-18-48.png](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/a1733e7c-60bf-4c6d-b024-e0c7400df9b2)

**Comment by ENDK-RHC** [comment]
RHC - Testet ok. Aktør ID og Aktør navn vises.
